version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd terraform_code
      - aws s3 cp s3://codebuild-bucket-1982/.env .env

  build:
    commands:
      - |
        if [[ $TF_ACTION == 'destroy' ]]; then
          make destroy-auto-approve TF_TARGET=$TF_VAR_TARGET
        else
          make deploy-auto-approve TF_TARGET=$TF_VAR_TARGET
        fi
      
  post_build:
    commands:
      - echo terraform completed on `date`