version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      # copy env var file
      - aws s3 cp s3://codebuild-bucket-1982/.env .env
      - docker-compose run terraform version

  build:
    commands:
      - docker-compose run terraform init
      - docker-compose run terraform plan -out terraform.tfplan
      - docker-compose run terraform apply "terraform.tfplan"
      
  post_build:
    commands:
      - echo terraform completed on `date`