version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      # - cd terraform_code
      - ls -larth
      - docker-compose run terraform version

  build:
    commands:
      - ls -larth
      - docker-compose run terraform init

  post_build:
    commands:
      - echo terraform completed on `date`