version: 0.2

phases:

  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd terraform_code
      - aws s3 cp s3://codebuild-bucket-1982/.env .env

  build:
    commands:
      - docker-compose run terraform init $TF_VAR_TARGET
      - docker-compose run terraform plan -out terraform.tfplan $TF_VAR_TARGET
      - docker-compose run terraform apply terraform.tfplan
      
  post_build:
    commands:
      - echo terraform completed on `date`